name: CAT_A_01
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROJECTS: RBS_LoanAccountDetails_v2 RBS_FetchFXDealList_v1 RBS_FetchBeneficiaryBanksList_v1 RBS_EnquireBeneficiaryDetails_v1 RBS_FXRateInquiry_v3 RBS_AccountBalanceDetails_v1
jobs:
  build:
    runs-on: self-hosted
    steps:
      
      - name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
            token: ${{secrets.github_token}}  
      - uses: actions/checkout@v2

        
      - name: Create Bars Folder
        run: mkdir bars
        
      - name: Build All Projects One By One
        run: for f in $PROJECTS; do echo Building $f Application; cd $f ;ant -noinput -buildfile build.xml ;mv /root/*.bar ../bars/$f_${{ steps.buildnumber.outputs.build_number }}.bar; cd ../;done
          
      - name: Check Bars Folder Existance
        run: |
          cd bars
          ls 
          mkdir /root/bars/dummy
          rm -r /root/bars/*
          cp *.bar /root/bars
      
      - name: Docker Build Image for repo ${{ github.repository }} of build number ${{ steps.buildnumber.outputs.build_number }}
        run: |
          docker build -t cat_a_011:v_${{ steps.buildnumber.outputs.build_number }} -f /root/dockerfile5 .
          rm -r /root/bars/*
          docker images
